server:
  port: 8765
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: userById
          uri: lb://company-users-service
          predicates:
            - Path=/company-users-service/api/users/{userId}
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/company-users-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: userById
          uri: lb://company-users-service
          predicates:
            - Path=/company-users-service/api/users/{userId}
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/company-users-service/(?<segment>.*), /$\{segment}
        - id: userById
          uri: lb://company-users-service
          predicates:
            - Path=/company-users-service/api/users/{userId}
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/company-users-service/(?<segment>.*), /$\{segment}
        - id: userById
          uri: lb://company-users-service
          predicates:
            - Path=/company-users-service/api/users/{userId}
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/company-users-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: users-actuator
          uri: lb://company-users-service
          predicates:
            - Path=/company-users-service/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/company-users-service/(?<segment>.*), /$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/