server:
  port: 8765
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userById
          uri: lb://company-users-service
          predicates:
            - Path=/api/users/{userid}
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

