server:
  port: 8765
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id:
          uri:
          predicates:
            -



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

